### ISSUE TITLE
Reaction to network status changed

### ISSUE THREAD

**Issue by detecyang** [madsolar8582/SLRNetworkMonitor#2]
I tested it and Reachability, launch app in No-network, then connected WiFi. I found SLRNetworkMonitor is always about 0.5 seconds slower than Reachability. What is the possible reason?

**Comment by madsolar8582** [comment]
Hi @detecyang. Without being able to see the internals of Apple's code, I can only guess as to why the two implementations are different. The SystemConfiguration framework was created before the existence of GCD, so it leverages function pointers rather than blocks (so I'm assuming there are no dispatches). The Network framework does use a dispatch queue to process updates, so the system will have to dispatch in order to process updates.

From the code that I wrote, the network monitor uses a dispatch queue with a QoS class of Utility. This means that it will yield to other scheduled work. After the work is done on the work queue, there is another dispatch to the main queue to post the notification, so depending on how busy the main queue is, there could be some time lost there.

The API I provide does allow you to provide your own dispatch queue for the work queue, so if you would like to create a queue with a higher QoS setting, that may change the behavior of the network monitoring.

**Comment by detecyang** [comment]
Thanks, I will try.
